version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21
  build:
    commands:
      - echo "Iniciando Migrates"
      - docker compose exec server bash -c 'npx sequelize db:migrate'
      - echo "Finalizado Migrates"