services:
  server:
    env_file: .env
    image: 148761658767.dkr.ecr.us-east-1.amazonaws.com/prod-meddiflux:latest
    container_name: meddiflux
    ports:
      - "80:8080" 
    #environment:
      #DB_HOST: $DB_HOST
      #DB_PORT: 5432
      #DB_SECRET_NAME: $DB_SECRET_NAME
      #DB_REGION: us-east-1