version: '3.7'

services:
  server:
    env_file: .env  # Certifique-se de que o .env está corretamente configurado no seu projeto
    image: 148761658767.dkr.ecr.us-east-1.amazonaws.com/hom-meddiflux:latest
    container_name: meddiflux
    ports:
      - "80:8080"  # Mapear a porta do contêiner para a porta 80
